all: mystat myls mytail myfind

mystat: mystat.c
	clang -g -Wall -o mystat mystat.c

myls: myls.c
	clang -g -Wall -o myls myls.c

mytail: mytail.c
	clang -g -Wall -o mytail mytail.c

myfind: myfind.c
	clang -g -Wall -o myfind myfind.c
